name: Daily Script

on:
  schedule:
    - cron: "30 3 * * *"  # 9:00 AM IST = 3:30 AM UTC
  workflow_dispatch:  # allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python main.py
        env:
          OWM_API_KEY: ${{ secrets.OWM_API_KEY }}
          ACCOUNT_SID: ${{ secrets.ACCOUNT_SID }}
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}

          MY_LAN: ${{ secrets.MY_LAT }}
          MY_LON: ${{ secrets.MY_LON }}

          MY_LAT: ${{ secrets.MY_LAT }}
          MY_LON: ${{ secrets.MY_LOM }}
